services:
    postgres_chat:
        container_name: postgres_chat
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: chatdb
            PGDATA: /var/lib/postgresql/data
        volumes:
            - chat-service-db-data:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        restart: always

    postgres_user:
        container_name: postgres_user
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: userdb
            PGDATA: /var/lib/postgresql/data
        volumes:
            - user-service-db-data:/var/lib/postgresql/data
        ports:
            - "5434:5432"
        restart: always

    postgres_tweet:
        container_name: postgres_tweet
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: tweetdb
            PGDATA: /var/lib/postgresql/data
        volumes:
            - tweet-service-db-data:/var/lib/postgresql/data
        ports:
            - "5435:5432"
        restart: always

    postgres_notification:
        container_name: postgres_notification
        image: postgres:latest
        environment:
            POSTGRES_DB: notificationdb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
        ports:
            - "5437:5432"
        volumes:
            - notification-service-db-data:/var/lib/postgresql/data
        restart: always

    zipkin:
        image: openzipkin/zipkin
        container_name: zipkin
        ports:
            - "9411:9411"
        networks:
            - spring

    rabbitmq:
        image: rabbitmq:3.9.11-management-alpine
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - spring

    zookeeper:
        image: confluentinc/cp-zookeeper:7.0.1
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - spring

    broker:
        image: confluentinc/cp-kafka:7.0.1
        container_name: broker
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        networks:
            - spring

#    eureka-server:
#        image: merikbest/twitter-spring-reactjs:eureka-server
#        container_name: eureka-server
#        hostname: eureka-server
#        environment:
#            EUREKA_HOST: eureka-server
#            ZIPKIN_HOST: zipkin
#        ports:
#            - "8761:8761"
#        networks:
#            - spring
#        depends_on:
#            - zipkin
#
#    config-server:
#        image: merikbest/twitter-spring-reactjs:config-server
#        container_name: config-server
#        hostname: config-server
#        environment:
#            EUREKA_HOST: eureka-server
#            ZIPKIN_HOST: zipkin
#        ports:
#            - "8888:8888"
#        networks:
#            - spring
#        depends_on:
#            - zipkin
#            - eureka-server
#
#    api-gateway:
#        image: merikbest/twitter-spring-reactjs:api-gateway
#        container_name: api-gateway
#        hostname: api-gateway
#        environment:
#            EUREKA_HOST: eureka-server
#            CONFIG_SERVER_HOST: config-server
#            ZIPKIN_HOST: zipkin
#        ports:
#            - "8000:8000"
#        networks:
#            - spring
#        depends_on:
#            - zipkin
#            - eureka-server
#            - config-server
#
#    user-service:
#        image: merikbest/twitter-spring-reactjs:user-service
#        container_name: user-service
#        hostname: user-service
#        environment:
#            EUREKA_HOST: eureka-server
#            CONFIG_SERVER_HOST: config-server
#            DATASOURCE_HOST: postgres
#            ZIPKIN_HOST: zipkin
#            RABBITMQ_HOST: rabbitmq
#        ports:
#            - "8001:8001"
#        networks:
#            - postgres
#            - spring
#        depends_on:
#            - postgres
#            - zipkin
#            - rabbitmq
#            - broker
#            - eureka-server
#            - config-server
#
#    tweet-service:
#        image: merikbest/twitter-spring-reactjs:tweet-service
#        container_name: tweet-service
#        hostname: tweet-service
#        environment:
#            EUREKA_HOST: eureka-server
#            CONFIG_SERVER_HOST: config-server
#            DATASOURCE_HOST: postgres
#            ZIPKIN_HOST: zipkin
#            RABBITMQ_HOST: rabbitmq
#        ports:
#            - "8002:8002"
#        networks:
#            - postgres
#            - spring
#        depends_on:
#            - postgres
#            - zipkin
#            - rabbitmq
#            - eureka-server
#            - config-server
#
#    topic-service:
#        image: merikbest/twitter-spring-reactjs:topic-service
#        container_name: topic-service
#        hostname: topic-service
#        environment:
#            EUREKA_HOST: eureka-server
#            CONFIG_SERVER_HOST: config-server
#            DATASOURCE_HOST: postgres
#            ZIPKIN_HOST: zipkin
#            RABBITMQ_HOST: rabbitmq
#        ports:
#            - "8003:8003"
#        networks:
#            - postgres
#            - spring
#        depends_on:
#            - postgres
#            - zipkin
#            - rabbitmq
#            - broker
#            - eureka-server
#            - config-server
#
#    tag-service:
#        image: merikbest/twitter-spring-reactjs:tag-service
#        container_name: tag-service
#        hostname: tag-service
#        environment:
#            EUREKA_HOST: eureka-server
#            CONFIG_SERVER_HOST: config-server
#            DATASOURCE_HOST: postgres
#            ZIPKIN_HOST: zipkin
#            RABBITMQ_HOST: rabbitmq
#        ports:
#            - "8004:8004"
#        networks:
#            - postgres
#            - spring
#        depends_on:
#            - postgres
#            - zipkin
#            - rabbitmq
#            - eureka-server
#            - config-server
#
#    lists-service:
#        image: merikbest/twitter-spring-reactjs:lists-service
#        container_name: lists-service
#        hostname: lists-service
#        environment:
#            EUREKA_HOST: eureka-server
#            CONFIG_SERVER_HOST: config-server
#            DATASOURCE_HOST: postgres
#            ZIPKIN_HOST: zipkin
#            RABBITMQ_HOST: rabbitmq
#        ports:
#            - "8005:8005"
#        networks:
#            - postgres
#            - spring
#        depends_on:
#            - postgres
#            - zipkin
#            - rabbitmq
#            - eureka-server
#            - config-server
#
#    chat-service:
#        image: merikbest/twitter-spring-reactjs:chat-service
#        container_name: chat-service
#        hostname: chat-service
#        environment:
#            EUREKA_HOST: eureka-server
#            CONFIG_SERVER_HOST: config-server
#            DATASOURCE_HOST: postgres
#            ZIPKIN_HOST: zipkin
#            RABBITMQ_HOST: rabbitmq
#        ports:
#            - "8006:8006"
#        networks:
#            - postgres
#            - spring
#        depends_on:
#            - postgres
#            - zipkin
#            - rabbitmq
#            - eureka-server
#            - config-server
#
#    notification-service:
#        image: merikbest/twitter-spring-reactjs:notification-service
#        container_name: notification-service
#        hostname: notification-service
#        environment:
#            EUREKA_HOST: eureka-server
#            CONFIG_SERVER_HOST: config-server
#            DATASOURCE_HOST: postgres
#            ZIPKIN_HOST: zipkin
#            RABBITMQ_HOST: rabbitmq
#        ports:
#            - "8007:8007"
#        networks:
#            - postgres
#            - spring
#        depends_on:
#            - postgres
#            - zipkin
#            - rabbitmq
#            - eureka-server
#            - config-server
#
#    email-service:
#        image: merikbest/twitter-spring-reactjs:email-service
#        container_name: email-service
#        hostname: email-service
#        environment:
#            EUREKA_HOST: eureka-server
#            CONFIG_SERVER_HOST: config-server
#            ZIPKIN_HOST: zipkin
#        ports:
#            - "8020:8020"
#        networks:
#            - spring
#        depends_on:
#            - zipkin
#            - eureka-server
#            - config-server
#
#    image-service:
#        image: merikbest/twitter-spring-reactjs:image-service
#        container_name: image-service
#        hostname: image-service
#        environment:
#            EUREKA_HOST: eureka-server
#            CONFIG_SERVER_HOST: config-server
#            ZIPKIN_HOST: zipkin
#        ports:
#            - "8021:8021"
#        networks:
#            - spring
#        depends_on:
#            - zipkin
#            - eureka-server
#            - config-server
#
#    websocket-service:
#        image: merikbest/twitter-spring-reactjs:websocket-service
#        container_name: websocket-service
#        hostname: websocket-service
#        environment:
#            EUREKA_HOST: eureka-server
#            CONFIG_SERVER_HOST: config-server
#            ZIPKIN_HOST: zipkin
#        ports:
#            - "8022:8022"
#        networks:
#            - spring
#        depends_on:
#            - zipkin
#            - eureka-server
#            - config-server

networks:
    postgres:
        driver: bridge
    spring:
        driver: bridge
    monitoring:

volumes:
    tag-service-db-data:
    user-service-db-data:
    list-service-db-data:
    chat-service-db-data:
    topic-service-db-data:
    notification-service-db-data:
    tweet-service-db-data: