server:
    port: 8020

spring:
    application:
        name: email-service
    zipkin:
        base-url: http://${ZIPKIN_HOST:localhost}:9411
    mail:
        host: smtp.gmail.com
        username: bive199@gmail.com
        password: qhws ytzy fyhj plaj
        port: 465
        protocol: smtps
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: email
mail:
    debug: false

eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        hostname: ${EUREKA_HOST:localhost}
